### ISSUE TITLE
Installation Problem 

### ISSUE THREAD

**Issue by Kawish-Ali** [sundaysec/Andspoilt#1]
While installing I got this error 
Installing.......

Traceback (most recent call last):
  File "./setup.py", line 61, in <module>
    subprocess.Popen("chmod +x /usr/share/metasploit-framework/tools/recon/ad_support.rb" % cwdpath, shell=True).wait()
TypeError: not all arguments converted during string formatting

**Comment by sundaysec** [comment]
Remove the unused aguement % cwdpath in line 61
New code:
`subprocess.Popen("chmod +x /usr/share/metasploit-framework/tools/recon/ad_support.rb" shell=True).wait()`
I will have to review the whole project....
Thanks!!!
